### ISSUE TITLE
Problem with FiveM (print)

### ISSUE THREAD

**Issue by beCoule** [N0rmie/fivem-lua-simple-xor-encrypt#1]
Hello i have a problem with this encrypt system, all is print in console when we do an action in game.
Please fix it remove print or give me an solution

Thank's

**Comment by N0rmie** [comment]
Hey, first try to re-encrypt the script because sometimes strings get broken (15% possibilities) and if that doesn’t fix the problem, fix your script because it may be probably an error of it. This system has been tested and works correctly. Can you send a screenshot of the “print” you are referring to?

**Comment by beCoule** [comment]
I have already re-encrypted and it still does it for me, it is printed in the txadmin console (server side). It prints all my encrypted server file

**Comment by N0rmie** [comment]
That is because your script has an error, try using it decrypted and find the error.

**Comment by beCoule** [comment]
There is no error though

**Comment by N0rmie** [comment]
There might be one, check all the code and try again…

**Comment by beCoule** [comment]
ok ok, i tell you later

**Comment by beCoule** [comment]
So, I try decrypt and there is no errors, is possible to disable it please. Delete print and when there is errors it print just line or nothing
